# Generated by Django 4.0.3 on 2022-08-29 05:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='blogs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('blog_name', models.CharField(max_length=50)),
                ('blog_title', models.CharField(max_length=200)),
                ('blog_details', models.CharField(max_length=200)),
                ('blog_comment', models.CharField(max_length=500)),
                ('blog_image', models.ImageField(upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='comments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comm_person_name', models.CharField(max_length=50)),
                ('comm_person_email', models.EmailField(max_length=150)),
                ('comm_person_website', models.URLField()),
                ('comm_detils', models.CharField(max_length=50)),
                ('comm_date', models.DateField()),
                ('comm_time', models.TimeField()),
                ('comm_person_image', models.ImageField(upload_to='')),
                ('commnts_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='userPanel.blogs')),
            ],
        ),
        migrations.CreateModel(
            name='community',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('com_name', models.CharField(max_length=50)),
                ('com_pragraph', models.CharField(max_length=150)),
                ('com_address', models.CharField(max_length=150)),
                ('com_details', models.CharField(max_length=500)),
                ('com_image', models.ImageField(upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cont_person_name', models.CharField(max_length=50)),
                ('cont_person_email', models.EmailField(max_length=150)),
                ('cont_person_subject', models.CharField(max_length=50)),
                ('cont_person_message', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='feature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('feat_name', models.CharField(max_length=50)),
                ('feat_title', models.CharField(max_length=200)),
                ('feat_pragraph', models.CharField(max_length=500)),
                ('feat_image', models.ImageField(upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='found',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fnd_title', models.CharField(max_length=200)),
                ('fnd_pragraph', models.CharField(max_length=200)),
                ('fnd_image', models.ImageField(upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='guideline',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('guid_title', models.CharField(max_length=200)),
                ('guid_pragraph', models.CharField(max_length=500)),
                ('guid_file', models.FileField(upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='slider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sl_title', models.CharField(max_length=200)),
                ('sl_pragraph', models.CharField(max_length=200)),
                ('sl_image', models.ImageField(upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='subjects',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sub_name', models.CharField(max_length=50)),
                ('sub_fee', models.CharField(max_length=50)),
                ('sub_duration', models.CharField(max_length=50)),
                ('sub_details', models.CharField(max_length=500)),
                ('sub_image', models.ImageField(upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='tips',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tps_title', models.CharField(max_length=200)),
                ('tps_pragraph', models.CharField(max_length=500)),
                ('tps_line', models.CharField(max_length=200)),
                ('tps_file', models.FileField(upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='reply',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rply_person_name', models.CharField(max_length=50)),
                ('rply_details', models.CharField(max_length=50)),
                ('rply_date', models.DateField()),
                ('rply_time', models.TimeField()),
                ('rply_person_image', models.ImageField(upload_to='')),
                ('rply_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='userPanel.comments')),
            ],
        ),
    ]
