# Generated by Django 4.0.3 on 2022-08-29 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userPanel', '0002_alter_slider_sl_pragraph'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogs',
            name='blog_details',
            field=models.TextField(max_length=500),
        ),
        migrations.AlterField(
            model_name='comments',
            name='comm_detils',
            field=models.TextField(max_length=500),
        ),
        migrations.AlterField(
            model_name='community',
            name='com_details',
            field=models.TextField(max_length=500),
        ),
        migrations.AlterField(
            model_name='community',
            name='com_pragraph',
            field=models.TextField(max_length=500),
        ),
        migrations.AlterField(
            model_name='contact',
            name='cont_person_message',
            field=models.TextField(max_length=500),
        ),
        migrations.AlterField(
            model_name='feature',
            name='feat_pragraph',
            field=models.TextField(max_length=500),
        ),
        migrations.AlterField(
            model_name='guideline',
            name='guid_pragraph',
            field=models.TextField(max_length=500),
        ),
        migrations.AlterField(
            model_name='reply',
            name='rply_details',
            field=models.TextField(max_length=500),
        ),
        migrations.AlterField(
            model_name='slider',
            name='sl_pragraph',
            field=models.TextField(max_length=500),
        ),
        migrations.AlterField(
            model_name='subjects',
            name='sub_details',
            field=models.TextField(max_length=500),
        ),
        migrations.AlterField(
            model_name='tips',
            name='tps_pragraph',
            field=models.TextField(max_length=500),
        ),
    ]
