# Generated by Django 4.0.3 on 2022-09-02 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userPanel', '0004_alter_slider_sl_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogs',
            name='blog_details',
            field=models.TextField(max_length=1500),
        ),
    ]
