# Generated by Django 4.0.3 on 2022-09-07 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userPanel', '0006_guideline_date_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='guideline',
            name='date_time',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
